base_url = "https://michelletilley.net"
title = "Michelle Tilley"
description = "Personal blog"
default_language = "en"
compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]


[[taxonomies]]
name = "categories"
feed = true

[extra]
author = "Michelle Tilley"

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_external = true
smart_punctuation = false
bottom_footnotes = true
insert_anchor_links = "left"

[markdown.highlighting]
error_on_missing_language = false
style = "inline"
light_theme = "github-light"
dark_theme = "github-dark"
